### ISSUE TITLE
Cannot Download Torrent

### ISSUE THREAD

**Issue by S4RGE** [Yukariin/qBittorrent-Search-Plugins#4]
At the moment, when you click on a Torrent Link in the search result, the client takes up to 30 seconds and also freezes up until the message appears that the torrent file does not exists. But if you click on the go to website button. The page does exists and also the torrent file can be downloaded.

**Comment by edo44** [comment]
Same issue here
https://github.com/qbittorrent/qBittorrent/issues/4963

**Comment by Yukariin** [comment]
Fixed.
